version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      postgresql:
        patterns:
          - "*postgresql*"
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"
      jackson:
        patterns:
          - "jackson*"
          - "*jackson*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "kotlin*"
          - "*kotlin*"
      jackson:
        patterns:
          - "jackson*"
          - "*jackson*"
 
  - package-ecosystem: "gradle"
    directory: "/experiments"
    schedule:
      interval: "daily"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "kotlin*"
          - "*kotlin*"
      jackson:
        patterns:
          - "jackson*"
          - "*jackson*"
