version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/jeorg-kotlin-arrow-optics/jeorg-kotlin-arrow-optics-gradle-1"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/jeorg-kotlin-arrow-optics/jeorg-kotlin-optics-crums-1"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/experiments"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/jeorg-kotlin-apps/jeorg-microchip-maker/jeorg-microchip-maker-gui"
    schedule:
      interval: "daily"
