version: 2.1

jobs:
  build-and-test:
    docker:
      - image: eclipse-temurin:21-alpine
    steps:
      - run: apk add maven
      - checkout
      - run: mvn clean install jacoco:prepare-agent package jacoco:report

workflows:
  sample:
    jobs:
      - build-and-test
