version: 2.1

jobs:
  build-and-test:
    docker:
      - image: eclipse-temurin:21-alpine
    steps:
      - run: apk add maven make
      - run: apk update && apk upgrade
      - checkout
      - run: make build-maven

workflows:
  sample:
    jobs:
      - build-and-test
