version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run: mvn clean install jacoco:prepare-agent package jacoco:report

workflows:
  sample:
    jobs:
      - build-and-test
